{% set name = "idds-client" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 50138ce08f38ac5602ccac51f09d20bead5121a83e5beb83dee569055b6868d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - python >=3.6
    - requests
    - tabulate
    - urllib3
    - argcomplete

test:
  imports:
    - idds
    - idds.client

about:
  home: https://pypi.org/project/idds-client/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
