{% set name = "idds-client" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c176566c9a2f5fe7f56eab9d235825b672d194751a456d877a6eb7538dee4143

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - python >=3.6
    - requests
    - stomp.py
    - tabulate
    - urllib3
    - argcomplete

test:
  imports:
    - idds
    - idds.client

about:
  home: https://pypi.org/project/idds-client/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
