{% set name = "idds-client" %}
{% set name_pypi = "idds_client" %}
{% set version = "2.2.39" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name_pypi }}/{{ name_pypi }}-{{ version }}.tar.gz
  sha256: ad1c3499c8d3617b725836af46e70b1e25414b8f9c52f27d0c675a50a2d261db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - idds-common =={{ version }}
    - idds-workflow =={{ version }}
    - python >={{ python_min }}
    - requests
    - tabulate
    - urllib3
    - argcomplete

test:
  requires:
    - python {{ python_min }}
  imports:
    - idds
    - idds.client

about:
  home: https://pypi.org/project/idds-client/
  summary: intelligent Data Delivery Service(iDDS) Package
  dev_url: https://github.com/HSF/iDDS
  license: Apache-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - wguanicedew
    - yesw2000
